services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: izihub
      POSTGRES_PASSWORD: izihub
      POSTGRES_DB: izihub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U izihub -d izihub_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      MIX_ENV: dev
      PHX_DOCKER: true
      PHX_HOST: localhost
      PORT: 4000
      DATABASE_URL: ecto://izihub:izihub@db:5432/izihub_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: izihub
      POSTGRES_PASSWORD: izihub
      POSTGRES_DB: izihub_db
    volumes:
      - .:/app
      - deps:/app/deps
      - build:/app/_build
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  deps:
  build:
